### ISSUE TITLE
Multipart upload image along with other text fileds

### ISSUE THREAD

**Issue by nowfalsalahudeen** [jaychang0917/SimpleApiClient#5]
how can i upload a image file along with other text strings

@POST("/user/profile/update")
    fun updateProfile(@Header("Authorization") headerAuth: String,
                      @Body @MultiPart(name = "image", mimeType = "image/*") file: Uri,
                      @Part("name")name: String,
                      @Part("email")email: String): Observable<String>

this code gives error

**Comment by jaychang0917** [comment]
What error you get? You should use `RequestBody` instead of `String` since only `Uri` type is handled by this library. 

E.g.
 ```kotlin
fun updateProfile(@Header("Authorization") headerAuth: String,
@Body @Multipart(name = "image", mimeType = "image/*") file: Uri,
@Part("name")name: RequestBody,
@Part("email")email: RequestBody): Observable
```

**Comment by nowfalsalahudeen** [comment]
thanx will check it and inform back to you

**Comment by nowfalsalahudeen** [comment]
How can i create requestbody ??
in kotlin

val emailtxt = RequestBody.create(MediaType.parse("text/plain"), name.text,toString())
it will gives error
and also how can cast string to RequstBody??

**Comment by nowfalsalahudeen** [comment]
this is i got..

java.lang.IllegalArgumentException: @Part parameters can only be used with multipart encoding. (parameter #3)
                                                                             for method EkalawyaApi.updateProfile
                                                                             at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:752)
                                                                             at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:743)
                                                                             at retrofit2.ServiceMethod$Builder.parameterError(ServiceMethod.java:761)
                                                                             at retrofit2.ServiceMethod$Builder.parseParameterAnnotation(ServiceMethod.java:592)
                                                                             at retrofit2.ServiceMethod$Builder.parseParameter(ServiceMethod.java:336)
                                                                             at retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:204)
                                                                             at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:170)
                                                                             at retrofit2.Retrofit$1.invoke(Retrofit.java:147)
                                                                             at java.lang.reflect.Proxy.invoke(Proxy.java:913)
                                                                             at $Proxy0.updateProfile(Unknown Source)


code i have used.
@POST("/user/profile/update")
    fun updateProfile(@Header("Authorization") headerAuth: String,
                      @Body @MultiPart(name = "image", mimeType = "image/*") file: Uri,
                      @Part("name")name: RequestBody,
                      @Part("email")email: RequestBody): Observable<String>


Api.create().updateProfile("UserToken",
                pickedImage, //Uri
                RequestBody.create(MediaType.parse("text/plain"), name.text.toString()),
                RequestBody.create(MediaType.parse("text/plain"), email.text.toString())).observe(
                onStart = {

                },
                onEnd = {

                },
                onError = {
                    println(it.message)
                },
                onSuccess = {
                    println(it)
                }
        )
