### ISSUE TITLE
Multipart upload image along with other text fileds

### ISSUE THREAD

**Issue by nowfalsalahudeen** [jaychang0917/SimpleApiClient#6]
sorry i unexpectedly closed that issue
this is i got..

java.lang.IllegalArgumentException: @Part parameters can only be used with multipart encoding. (parameter #3)
                                                                             for method EkalawyaApi.updateProfile
                                                                             at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:752)
                                                                             at retrofit2.ServiceMethod$Builder.methodError(ServiceMethod.java:743)
                                                                             at retrofit2.ServiceMethod$Builder.parameterError(ServiceMethod.java:761)
                                                                             at retrofit2.ServiceMethod$Builder.parseParameterAnnotation(ServiceMethod.java:592)
                                                                             at retrofit2.ServiceMethod$Builder.parseParameter(ServiceMethod.java:336)
                                                                             at retrofit2.ServiceMethod$Builder.build(ServiceMethod.java:204)
                                                                             at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:170)
                                                                             at retrofit2.Retrofit$1.invoke(Retrofit.java:147)
                                                                             at java.lang.reflect.Proxy.invoke(Proxy.java:913)
                                                                             at $Proxy0.updateProfile(Unknown Source)

code i have used.
@POST("/user/profile/update")
    fun updateProfile(@Header("Authorization") headerAuth: String,
                      @Body @MultiPart(name = "image", mimeType = "image/*") file: Uri,
                      @Part("name")name: RequestBody,
                      @Part("email")email: RequestBody): Observable<String>

Api.create().updateProfile("UserToken",
                pickedImage, //Uri
                RequestBody.create(MediaType.parse("text/plain"), name.text.toString()),
                RequestBody.create(MediaType.parse("text/plain"), email.text.toString())).observe(
                onStart = {

                },
                onEnd = {

                },
                onError = {
                    println(it.message)
                },
                onSuccess = {
                    println(it)
                }
        )

**Comment by jaychang0917** [comment]
Try to annotate your method with `@Multipart` which is a retrofit annotation.
